### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by phdru**

### CODE REVIEW

**Comment by jlebon** [comment]
Thanks! Can you just make the commit message titles lower case?

Random aside: looks like your email might not be associated with your GitHub username? E.g. GitHub says "Oleg Broytman authored and phdru committed" on the first two commits.

**Comment by phdru** [comment]
> Thanks! Can you just make the commit message titles lower case?

Completely lower case or title case?

    Style(native): fix flake8 warnings 

or

    style(native): fix flake8 warnings 

???

> Random aside: looks like your email might not be associated with your GitHub username? E.g. GitHub says "Oleg Broytman authored and phdru committed" on the first two commits.

Ah, thank you for spotting! That's my work email. Will fix it.

**Comment by jlebon** [comment]
> `style(native): fix flake8 warnings`

That one. :)

**Comment by phdru** [comment]
Done. :smiley:

**Comment by jlebon** [comment]
Awesome, thanks!

**Pull request merged**
